# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eee97e4bb1d5018251bcd921cf2839c7f301b1f59c672854e5b80da59ea06bd5d0ec9c2d23226eaf56f7b380ccf969846d8d487d4f623b8e8feb2654f8e489df

test:
  secret_key_base: d37ade1765cdc3c2e6c321add8c7cf2ecb2189b29f8ce71445496510fda1f011eef63a2417af3d1b9232fb948ac349b4eca19ec05de3309693824b19cfa309ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
